### PR TITLE
Fix: clean up old space image

### LINKED ISSUE #11821: Space images are kept forever
## Describe the bug
When you create a space you can edit the space image. You can set different images for the same space for a long time. However, the old images aren't removed from the space, and might take a lot of storage space.

## Steps to reproduce
1. Create a space
2. Edit the space image multiple times, use different images each time.
3.

## Expected behavior
Only the last uploaded image is kept. The previous images are gone.

## Actual behavior
Although the last uploaded image is shown, all the images are kept. You can find the previously uploaded files inside the backend storage.

## Setup
Please describe how you started the server and provide a list of relevant environment variables or configuration files.

<details>
<p>

```console
OCIS_XXX=somevalue
OCIS_YYY=somevalue
PROXY_XXX=somevalue
```

</p>
</details>

### PR DESCRIPTION
**Pull request by max65482**
Currently, old space images are not cleaned up and take up storage space. They are a "memory leak". With this PR, the previous space image is deleted upon setting a new one.

Fixes https://github.com/owncloud/ocis/issues/11821

### CODE REVIEW

File: pkg/storage/utils/decomposedfs/spaces.go [hunk 1]
```diff
@@ -676,6 +676,22 @@ func (fs *Decomposedfs) UpdateStorageSpace(ctx context.Context, req *provider.Up
...
+	if newImageID, ok := metadata[prefixes.SpaceImageAttr]; ok {
+		oldImageID, err := spaceNode.XattrString(ctx, prefixes.SpaceImageAttr)
+		if err == nil && oldImageID != "" && oldImageID != string(newImageID) {
+			delRef := &provider.Reference{
+				ResourceId: &provider.ResourceId{
+					SpaceId:  spaceID,
+					OpaqueId: oldImageID,
+				},
+			}
+			fs.Delete(ctx, delRef)
```
Comment (kobergj) [inline pkg/storage/utils/decomposedfs/spaces.go]: I think we should only actually delete the old image when setting the new one was successful. So we should move this to after the `spaceNode.SetXattrsWithContext(ctx, metadata, true)` call. 

Reason for this is that if setting the new image fails out of some reason we would have deleted the old one already.

**Review by kobergj — CHANGES_REQUESTED** [review]
@max65482 very good idea. I like the approach. Just one small comment. 

And could I also ask you to add a changelog to this PR? We need to keep track of changes for the next release. See for example this old PR: https://github.com/owncloud/reva/pull/443/changes#diff-1428f49bdd09346722ee0d07b93800829abdc5f8c142cf0b7bf2fd62bb8bf0e9

File: pkg/storage/utils/decomposedfs/spaces.go (hunk 1 above)
Comment (max65482) [reply pkg/storage/utils/decomposedfs/spaces.go]: Fixed.

**Comment by max65482** [comment]
Ok, implemented your suggestion and added changelog.

**Review by kobergj — APPROVED** [review]
I love it ❤️  Thank you for your contribution!
